language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: 5.2
    - php: nightly
    - php: hhvm

before_script:
  - ./build.sh

script:
  - phpunit --coverage-text tests
